### ISSUE TITLE
Add support of bundling binary resources

### ISSUE THREAD

**Issue by no1seman** [tarantool/lua-bundler-webpack-plugin#1]
It will be great if bundler will support binary resources and pre-ziping, for example like this:
https://github.com/no1seman/frontend-stub-flutter/blob/master/scripts/bundle.js
https://github.com/no1seman/frontend-stub-flutter/blob/master/plop-templates/index.lua.hbs

**Comment by usenko-timur** [comment]
PR: https://github.com/tarantool/frontend-tools/pull/5
